"""Chip-agnostic USB HID helpers shared across WCH chips."""

from .keycodes import (
    ASCII_TO_KEYCODE,
    SHIFT_FLAG,
    MODIFIER_BASE,
    is_modifier,
    modifier_bit,
    ascii_to_keycode,
)
from .modifiers import (
    MOD_NONE,
    MOD_LCTRL,
    MOD_LSHIFT,
    MOD_LALT,
    MOD_LGUI,
    MOD_LWIN,
    MOD_RCTRL,
    MOD_RSHIFT,
    MOD_RALT,
    MOD_RGUI,
    MOD_RWIN,
    modifier_name_to_bit,
    modifiers_to_byte,
    parse_modifiers,
)
from .report import keyboard_report, iter_text_reports, RELEASE_REPORT
from .keys import (
    SPECIAL_KEYS,
    US_CHAR_MAP,
    special_key_to_hid,
    char_to_hid,
    resolve_key,
    validate_chars,
    set_layout,
    get_layout,
    build_char_map,
    register_layout,
    available_layouts,
)
from .layouts import load_layout_yaml, get_overrides, ENV_LAYOUTS_DIR

__all__ = [
    "ASCII_TO_KEYCODE",
    "SHIFT_FLAG",
    "MODIFIER_BASE",
    "is_modifier",
    "modifier_bit",
    "ascii_to_keycode",
    "MOD_NONE",
    "MOD_LCTRL",
    "MOD_LSHIFT",
    "MOD_LALT",
    "MOD_LGUI",
    "MOD_LWIN",
    "MOD_RCTRL",
    "MOD_RSHIFT",
    "MOD_RALT",
    "MOD_RGUI",
    "MOD_RWIN",
    "modifier_name_to_bit",
    "modifiers_to_byte",
    "parse_modifiers",
    "keyboard_report",
    "iter_text_reports",
    "RELEASE_REPORT",
    "SPECIAL_KEYS",
    "US_CHAR_MAP",
    "special_key_to_hid",
    "char_to_hid",
    "resolve_key",
    "validate_chars",
    "set_layout",
    "get_layout",
    "build_char_map",
    "register_layout",
    "available_layouts",
    "load_layout_yaml",
    "get_overrides",
    "ENV_LAYOUTS_DIR",
]
